In [22]:
from sklearn.datasets import load_iris

iris_data= load_iris()


In [4]:
iris_data.keys() #key값 확인 -> 딕셔너리 형태 

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [5]:
iris_data.values() #value값 확인

dict_values([array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
 

In [14]:
type(iris_data.feature_names) 
len(iris_data.feature_names)

4

In [9]:
iris_data.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [10]:
iris_data.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [15]:
# X_train = iris_data.data[:120] # 80%
# X_test = iris_data.data[120:] # 20%

In [17]:
# y_train = iris_data.target[:120]
# y_test = iris_data.target[120:]

## train_test_split
> sklearn.model_selection.train_test_split
* Split arrays or matrices into random train and test subsets(학습데이터와 테스트데이터 분리)
* train_test_split(*arrays, test_size=None, train_size=None, random_state=None, shuffle=True, stratify=None)

In [23]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris_data.data, iris_data.target, test_size=0.3, random_state=10)

### DecisionTreeClassifier
> sklearn.tree.DecisionTreeClassifier
* DecisionTreeClassifier(*, criterion='gini', splitter='best', max_depth=None, min_samples_split=2, min_samples_leaf=1, min_weight_fraction_leaf=0.0, max_features=None, random_state=None, max_leaf_nodes=None, min_impurity_decrease=0.0, class_weight=None, ccp_alpha=0.0)

In [38]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

dt_clf = DecisionTreeClassifier()
train_data = iris_data.data
train_label = iris_data.target
dt_clf.fit(train_data, train_label)

DecisionTreeClassifier()

### accuracy_score
* accuracy_score(y_true, y_pred, *, normalize=True, sample_weight=None)
* In multilabel classification, this function computes subset accuracy: the set of labels predicted for a sample must exactly match the corresponding set of labels in y_true.

In [39]:
pred = dt_clf.predict(train_data)
print(accuracy_score(train_label, pred))  

1.0


In [41]:
dt_clf = DecisionTreeClassifier(max_depth=2, random_state=11)
X_train, X_test, y_train, y_test = train_test_split(iris_data.data, iris_data.target, test_size=0.3, random_state=121)
# 초매개변수 (hyper parameter)
dt_clf.fit(X_train, y_train)
pred = dt_clf.predict(X_test)
print(accuracy_score(y_test, pred))

0.9555555555555556


## overfiting / underfiting

### 중첩 fold

### KFold 교차검증
> sklearn.model_selection.KFold
* KFold(n_splits=5, *, shuffle=False, random_state=None)
* K-Folds cross-validator(교차검증) : Provides train/test indices to split data in train/test sets. Split dataset into k consecutive folds (without shuffling by default). Each fold is then used once as a validation while the k - 1 remaining folds form the training set

In [56]:
from sklearn.model_selection import KFold
import numpy
features = iris_data.data
label = iris_data.target
dt_clf = DecisionTreeClassifier(random_state=156)

# 5개의 폴드 세트로 분리하는 KFold 객체와 폴드 세트별 정확도를 담을 리스트 객체 생성
kfold = KFold(n_splits=5)
cv_accuracy = []
print(features.shape[0])

150


In [61]:
n_iter = 0
# KFold 객체의 split() 호출 시, 폴드 별 학습용, 검증용 테스트의 로우 인덱스를 array로 반환
for train_index, test_index in kfold.split(features):
    X_train, X_test = features[train_index], features[test_index]
    y_train, y_test = label[train_index], label[test_index]
    # 학습 및 예측
    dt_clf.fit(X_train, y_train)
    pred = dt_clf.predict(X_test)
    n_iter += 1
    # 반복할 때마다 정확도 측정
    accuracy = np.round(accuracy_score(y_test, pred), 4)
    train_size = X_train.shape[0]
    test_size = X_test.shape[0]
    print(n_iter, accuracy, train_size, test_size)
    print(n_iter, test_index)
    cv_accuracy.append(accuracy)
    print()
# 개별 itration별 정확도를 합하여 평균 정확도 계산
print(np.mean(cv_accuracy))

1 1.0 120 30
1 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

2 0.9667 120 30
2 [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]

3 0.8667 120 30
3 [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
 84 85 86 87 88 89]

4 0.9333 120 30
4 [ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]

5 0.7333 120 30
5 [120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]

0.9


### Stratified KFold

In [62]:
import pandas as pd 

In [64]:
iris_df = pd.DataFrame(data = iris_data.data, columns=iris_data.feature_names)
iris_df['label'] = iris_data.target
iris_df['label'].value_counts()

0    50
1    50
2    50
Name: label, dtype: int64

In [95]:
kfold = KFold(n_splits=3)
dt_clf = DecisionTreeClassifier(random_state=121)
n_iter = 0
for train_index, test_index in kfold.split(iris_df):
    n_iter += 1
    
    label_train = iris_df['label'].iloc[train_index]
    label_test = iris_df['label'].iloc[test_index]
    
    X_train, X_test = features[train_index], features[test_index]
    y_train, y_test = label[train_index], label[test_index]
    
    print('교차검증:', n_iter)
    print(label_train.value_counts())
    print(label_test.value_counts())
    dt_clf.fit(X_train, y_train)
    pred = dt_clf.predict(X_test)
    print(pred)
    print(np.round(accuracy_score(y_test, pred), 4))

교차검증: 1
1    50
2    50
Name: label, dtype: int64
0    50
Name: label, dtype: int64
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1]
0.0
교차검증: 2
0    50
2    50
Name: label, dtype: int64
1    50
Name: label, dtype: int64
[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 0 2]
0.0
교차검증: 3
0    50
1    50
Name: label, dtype: int64
2    50
Name: label, dtype: int64
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1]
0.0


from sklearn.model_selection import StratifiedKFold
skf = StratifiedKFold(n_splits=3)
dt_clf = DecisionTreeClassifier(random_state=156)
n_iter = 0
cv_accuracy = []

for train_index, test_index in skf.split(features, label):
    n_iter += 1

    X_train, X_test = features[train_index], features[test_index]
    y_train, y_test = label[train_index], label[test_index]
    
    train_size = X_train.shape[0]
    test_size = X_test.shape[0]
                               
    
    dt_clf.fit(X_train, y_train)
    pred = dt_clf.predict(X_test)
    accuracy = np.round(accuracy_score(y_test, pred), 4)
    
    print('교차검증:', n_iter)
    print(accuracy, train_size, test_size)
    print(test_index)
    cv_accuracy.append(accuracy)

print(np.round(cv_accuracy, 2))
print(np.round(np.mean(cv_accuracy),4))

### cross_val_score()
> sklearn.model_selection.cross_val_score
* cross_val_score(estimator(판단 알고리즘), X, y=None, *, groups=None, scoring=None, cv=None, n_jobs=None, verbose=0, fit_params=None, pre_dispatch='2*n_jobs', error_score=nan)

In [108]:
from sklearn.model_selection import cross_val_score
dt_clf = DecisionTreeClassifier(random_state=156)
data = iris_data.data
label = iris_data.target

# 성능지표는 정확도, 교차 검증 세트는 3개 
scores = cross_val_score(dt_clf, data, label, scoring='accuracy', cv=3)
# cv -> fold 횟수
# 알고리즘이 dt_clf 이기 때문에 y값을 요구함 
print(np.round(scores,4))
print(np.round(np.mean(scores), 4))

[0.98 0.94 0.98]
0.9667


## GridSearchCV
> sklearn.model_selection.GridSearchCV
* GridSearchCV(estimator, param_grid, *, scoring=None, n_jobs=None, refit=True, cv=None, verbose=0, pre_dispatch='2*n_jobs', error_score=nan, return_train_score=False)

In [110]:
from sklearn.model_selection import GridSearchCV
import pandas as pd

In [126]:
X_train, X_test, y_train, y_test = train_test_split(iris_data.data, iris_data.target, test_size=0.2, random_state=121)
dtree = DecisionTreeClassifier()
parameters = {'max_depth':[1,2,3,4], 'min_samples_split':[2,3]}

In [127]:
grid_dtree = GridSearchCV(dtree, param_grid=parameters, cv=3, refit=True)
grid_dtree.fit(X_train, y_train)

GridSearchCV(cv=3, estimator=DecisionTreeClassifier(),
             param_grid={'max_depth': [1, 2, 3, 4],
                         'min_samples_split': [2, 3]})

In [128]:
scores_df = pd.DataFrame(grid_dtree.cv_results_)
scores_df[['params', 'mean_test_score', 'rank_test_score', \
          'split0_test_score', 'split1_test_score', 'split2_test_score']]

params  mean_test_score  rank_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}         0.700000                7   
1  {'max_depth': 1, 'min_samples_split': 3}         0.700000                7   
2  {'max_depth': 2, 'min_samples_split': 2}         0.958333                4   
3  {'max_depth': 2, 'min_samples_split': 3}         0.958333                4   
4  {'max_depth': 3, 'min_samples_split': 2}         0.975000                1   
5  {'max_depth': 3, 'min_samples_split': 3}         0.975000                1   
6  {'max_depth': 4, 'min_samples_split': 2}         0.950000                6   
7  {'max_depth': 4, 'min_samples_split': 3}         0.966667                3   

   split0_test_score  split1_test_score  split2_test_score  
0              0.700                0.7              0.700  
1              0.700                0.7              0.700  
2              0.925                1.0              0.950  
3              0.925                1.0              0.950  
4              0.975                1.0              0.950  
5              0.975                1.0              0.950  
6              0.925                1.0              0.925  
7              0.975                1.0              0.925

In [129]:
grid_dtree.best_params_

{'max_depth': 3, 'min_samples_split': 2}

In [131]:
X = [[5.2, 3.2, 1.3, 0.3]]
grid_dtree.predict(X)
# 세토사라고 예측 

array([0])

> 다음주는...
* 데이터 수집 -> 탐색적 분석 -> "전처리" -> 모델링 -> 평가 -> 모델링....
* preprocessing
